### ISSUE TITLE
How to get native Database connection from mongoist?

### ISSUE THREAD

**Issue by ChuanyuWang** [mongoist/mongoist#27]
Hi there,

I want to use mongoist in part of my application, in the rest places, I want to use native mongodb driver, how to get native Database connection from mongoist?

Regards,
Chuanyu

**Comment by ghmeier** [comment]
If you'd like, mongoist returns a native db connection from the [`connect`](https://github.com/saintedlama/mongoist/blob/master/lib/database.js#L95) function. So you something like the following would give you a mongoist and mongo native db connection:
```
const mongoist = require('mongoist');
const db = mongoist('mongodb://your_connection_string');
let nativeConnection = null;

db.connect().then((connection) => {
  nativeConnection = connection
});
```

**Comment by ChuanyuWang** [comment]
@ghmeier thanks for your support, issue closed.
