### ISSUE TITLE
The organization needs a logo

### ISSUE THREAD

**Issue by saintedlama** [mongoist/mongoist#32]
This logo is just not good enough

![image](https://user-images.githubusercontent.com/123820/67159668-1b233d80-f348-11e9-9e9f-9f8db6dcf6de.png)

I propose to replace the old logo with this

![image](https://user-images.githubusercontent.com/123820/67159674-355d1b80-f348-11e9-8709-915ed5272f2e.png)

**Comment by ghmeier** [comment]
I approve! Let's add it :)
