### ISSUE TITLE
How to declare mongoist in a module - ES6 style?

### ISSUE THREAD

**Issue by dotbloup** [mongoist/mongoist#57]
I used to declare the database connection like this in a module in the commonJS fashion:

```
const mongoist = require('mongoist'); 
const conn="mongodb://localhost:27017/data"; 
const options="";
module.exports = mongoist(conn,options);
```

Now, I can't make it work using ES6 as the following code does not work:

```
import * as mongoist from "mongoist"
const conn="mongodb://localhost:27017/data"; 
const options="";
export mongoist(conn,options);
On the import side, I use:
```

`import * as db from "./db.mjs"`

---------------

For sure, i could write "export {mongoist, conn, options};"

but then, in the main tread the following does not work: db.mongoist(db.conn,db.options)

i get the error 

TypeError: db.mongoist is not a function
    at file:///home/bit/test.js:3:13
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)

**Comment by ghmeier** [comment]
Hi @dotbloup - you should be able to import mongoist like this:
```
import mongoist from 'mongoist';

export mongoist('mongodb://localhost:27017/data', {});
```

We've been doing that for some time in our typescript code.
